kind: pipeline
name: deploy

steps:
  - name: hello
    image: dockerfile/nginx
    script: 
    - echo hello world

  - name: backend
    image: golang:1.16.3
    commands:
      - go build
      - go test 
      - echo $USERNAME > a.txt
      - cat a.txt



