kind: pipeline
name: deploy

steps:
  - name: hello
      image: dockerfile/nginx
      script: 
      - echo hello world
      
  - name: build
    image: golang:1.16.3
    commands:
      - go build

  - name: deploy
    image: alpine
    commands:
      - apk add --update openssh-client


