kind: pipeline
type: docker
name: default

trigger:
  branch:
    - master
    - develop
    - fix/*
    - feature/*

steps:
  - name: Load aws-cli
    image: alpine:latest
    command:
      - apk update
      - apk add --no-cache awscli
      - apk add --no-cache jq
      - aws secretsmanager get-secret-value --secret-id drone --query SecretString --output text | jq -r 'to_entries|map("\(.key)=\(.value)")|.[]' > app.env
      
  - name: publish  
    image: plugins/ecr
    settings:
      access_key: 
        from_secret: docker_username
      secret_key: 
        from_secret: docker_password
      repo: andy_trainings
      registry: 520096271983.dkr.ecr.us-east-1.amazonaws.com
      region: us-east-1
    
  - name: testpostgres
    image: postgres:9-alpine
    commands:
      - sleep 5 #give the service some time to start
      - psql -U postgres -d dbexample -h database

  - name: build
    image: golang:latest
    commands:
      - go build main.go

  - name: test
    image: golang:latest
    commands:
      - go test ./app/http/controller
      - go test ./app/http/middleware
      - go test ./app/repository
      - go test ./app/service

  # - name: testdeploydatabase
  #   image: golang:latest
  #   environment:
  #     DB_HOST: database
  #     DB_DRIVER: postgres
  #     DB_USER: postgres
  #     DB_PASSWORD: Aa123456
  #     DB_NAME: dbexample
  #     DB_PORT: 5432
  #   commands:
  #     - ./main -h database deploy

services:
  - name: database
    image: postgres:9-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbexample
      POSTGRES_HOST_AUTH_METHOD: trust
      
  # - name: publish_to_prod
  #   image: plugins/docker
  #   settings:
  #     registry: localhost:8000
  #     repo: localhost:8000/app
# steps:   
#   - name: publish_to_prod
#     image: plugins/docker
#       commands:
#         - docker compose up
#     settings:
#       registry: 697d-61-31-138-103.ngrok-free.app
#       repo: 697d-61-31-138-103.ngrok-free.app
  
#   - name: publish
#     pull: always
#     image: plugins/docker
#     settings:
#       auto_tag: true
#       auto_tag_suffix: linux-amd64
#       cache_from: appleboy/gorush
#       daemon_off: false
#       dockerfile: docker/Dockerfile.linux.amd64
#       password:
#         from_secret: docker_password
#       repo: appleboy/rush
#       username:
#         from_secret: docker_username
  
# - name: deploy-staging
#   image: drone/drone-deploy
#   settings:
#     server: http://a7e0-61-31-138-103.ngrok-free.app
#     token:
#     from_secret: drone_token
#     repo: octocat/hello-world
#     build: 24
#     environment: staging
#   when:
#     event: deployment

# - name: deploy-production
#   image: drone/drone-deploy
#   settings:
#     server: htts://a7e0-61-31-138-103.ngrok-free.app
#     token:
#       from_secret: drone_token
#     repo: octocat/hello-world
#     build: 24
#     environment: production
#   when:
#      event: deployment