kind: pipeline
type: docker
name: default
steps:
- name: Clone repository0
  image: plugins/git
  settings:
    url: https://andy_101398:9f156f6176df8d05a5d6f2e41da40daa14332d94@git-scm.castlestech.cloud/andy_101398/AndyTraining.git
  commands:
    - git fetch origin +refs/heads/test/ci

steps:
- name: Clone repository
  image: plugins/git
  settings:
    skip_verify: true
    netrc: true
    Username: andy_101398
    username: andy_101398
    password: ${DRONE_SECRET_PASSWORD}
    token: 9f156f6176df8d05a5d6f2e41da40daa14332d94
  commands:
    - git fetch origin +refs/heads/test/ci:refs/remotes/origin/test/ci
  when:
    event:
      - push
      - pull_request
steps:
- name: test
  image: alpine
  commands:
  - echo hello
  - echo world
  