kind: pipeline
type: docker
name: default
steps:
  - name: Clone repository
    image: plugins/git
    settings:
      username: andy_101398
      password: ${DRONE_SECRET_PASSWORD}
      # 或者使用 token 而不是密碼
      # token: ${DRONE_SECRET_TOKEN}
    commands:
      - git fetch origin +refs/heads/test/ci:
    when:
      event:
        - push
        - pull_request
steps:
- name: test
  image: alpine
  commands:
  - echo hello
  - echo world
  