kind: pipeline
name: deploy

steps:
  - name: backend
    image: golang:latest
    commands:
      - go build
      - go test 
      - echo hello world
      - echo $USERNAME > a.txt
      - cat a.txt
