version: "3.8"

services:
  db:
    env_file:
        - "./.env"
    image: postgres:14-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '9525:5432'
    # volumes:
    #   - db:/var/lib/postgresql/data
    # - ./sql/test.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
        - server
  gin:
    env_file:
      - "./.env"
    image: andy_trainings
    container_name: gin
    build: .
    ports: 
      - 9528:8080 
    restart: on-failure
    volumes:
      - ./app/config:/usr/src/app/
    depends_on:
      - db    
    networks:
      - server
  redis:
    container_name: redis
    image: redis
    # Specify the redis.conf file to use and add a password.
    command: /usr/local/etc/redis/redis.conf
    # command: /usr/local/etc/redis/redis.conf --requirepass mypassword
    ports: 
      - "6379:6379"
    # map the volumes to that redis has the custom conf file from this project.
    volumes: 
      - /redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - server
  proxy:
    env_file:
      - "./.env"
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - ./nginx/www:/usr/share/nginx/html
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
      - ./nginx/cert:/etc/nginx/cert 
    networks:
      - server
    links:
      - gin
  drone-server:
    image: drone/drone:2
    container_name: drone-server
    ports:
      - 8000:80
    volumes:
      - ./drone:/data
    restart: always
    networks:
      - server
    environment:
      - DRONE_SERVER_HOST=localhost:8000 # drone server
      - DRONE_SERVER_PROTO=http
      - DRONE_RPC_SECRET=4985adfef1cfc9e3adbed5d161d13b0 #共用密碼
      - DRONE_GIT_ALWAYS_AUTH=true
      # Gitea
      - DRONE_GITEA_CLIENT_ID=508348f0-d581-4683-9d6c-3e774ea4f591 # client id
      - DRONE_GITEA_CLIENT_SECRET=508348f0-d581-4683-9d6c-3e774ea4f591 #client secret
      - DRONE_GITEA_SERVER=http://localhost:3000 # gitea server
  gitea-server:
    image: gitea/gitea:1.13.3
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - server
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
volumes:
  db:  
  gin:
  redis:
  proxy:
networks:
  server:
  gitea:
    external: false
 