version: "3.8"

services:
  db:
    env_file:
        - "./.env"
    image: postgres:14-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '9525:5432'
    # volumes:
    #   - db:/var/lib/postgresql/data
      # - ./sql/test.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
        - server
  redis:
    container_name: redis
    image: redis
    # Specify the redis.conf file to use and add a password.
    command: /usr/local/etc/redis/redis.conf
    # command: /usr/local/etc/redis/redis.conf --requirepass mypassword
    ports: 
      - "6379:6379"
    # map the volumes to that redis has the custom conf file from this project.
    volumes: 
      - /redis.conf:/usr/local/etc/redis/redis.conf
    depends_on:
      - db  
    networks:
      - server
  golang:
    env_file:
      - "./.env"
    image: andy_trainings
    container_name: golang
    build: .
    ports: 
      - 9528:8080 
    restart: on-failure
    volumes:
      - ./app/config:/usr/src/app/
    depends_on:
      - redis    
    networks:
      - server
  proxy:
    env_file:
      - "./.env"
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - ./nginx/www:/usr/share/nginx/html
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
      - ./nginx/cert:/etc/nginx/cert 
    depends_on:
      - golang
    networks:
      - server
# volumes:
#   db:  
#   golang:
#   redis:
#   proxy:
networks:
  server:
