version: "3.8"

services:
  db:
    env_file:
        - "./.env"
    image: postgres:14-alpine
    container_name: test_postgres
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '9525:5432'
    volumes:
      - db:/var/lib/postgresql/data
      # - ./sql/test.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
        - server
  redis:
    container_name: redis
    image: redis
    # Specify the redis.conf file to use and add a password.
    command: /usr/local/etc/redis/redis.conf
    ports: 
      - "6379:6379"
    # map the volumes to that redis has the custom conf file from this project.
    volumes: 
      - /redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - server
  api:
    env_file:
      - "./.env"
    image: andy_trainings
    container_name: example
    build: .
    ports: 
      - 9528:8080 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - db
      - redis    
    networks:
      - server
volumes:
  db:  
  api:

networks:
  server:
