apiVersion: v1
kind: Service
metadata:
  name: gin
spec:
  selector:
    app: gin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: gin
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379